apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-patient-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-patient
  template:
    metadata:
      labels:
        app: client-patient
    spec:
      containers:
        - name: client-patient
          image: gcr.io/PROJECT_ID/IMAGE:TAG
---
apiVersion: v1
kind: Service
metadata:
  name: client-patient-srv
spec:
  selector:
    app: client-patient
  ports:
    - name: client-patient
      protocol: TCP
      port: 3000
      targetPort: 3000