export const styleobj = {
  main: {
    backgroundColor: "#502E92",
    width: "100%",
    display: "flex",
  },
  infocontanier: {
    backgroundColor: "#502E92",
    height: "350px",
    width: "100%",
    // margin: "147px auto",
    display: "flex",
    justifyContent: "center",
  },
  pic: {
    height: "350px",
  },
  info: {
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
  },
  hello: {
    fontSize: "30px",
    color: "#fff",
  },
  name: {
    fontSize: "35px",
    fontWeight: "bold",
    color: "#fff",
    fontFamily: "Avenir_black !important",
  },
  about: {
    fontSize: "20px",
    wordBreak: "break-word",
    width: "calc(100% - 100px)",
    marginTop: "10px",
    color: "#FFFFFF",
  },
  button: {
    marginTop: "20px",
    border: "1px solid #FFFFFF",
    padding: "9px 36px",
    textTransform: "capitalize",
    "& span": {
      color: "#FFFFFF",
      fontSize: "18px",
    },
  },
  navigationdiv: {
    background: "red",
    display: "flex",
    justifyContent: "space-around",
    flexDirection: "row",
    width: "100%",
  },
  doctordiv: {
    backgroundColor: "#fff",
    width: "20vw",
    height: "30vh",
  },
  appointmentdiv: {
    backgroundColor: "#fff",
    width: "20vw",
    height: "30vh",
  },
  consultationdiv: {
    backgroundColor: "#fff",
    width: "20vw",
    height: "30vh",
  },
  reportdiv: {
    backgroundColor: "#fff",
    width: "20vw",
    height: "30vh",
  },
  //   Navigation Card

  Card: {
    width: "230px",
    height: "170px",
    boxShadow: "none",
    backgroundColor: "#F0F1F6",
    cursor: "pointer",
  },
  icon: {
    width: "30px",
    height: "30px",
    opacity: "1",
  },
  typotext: {
    color: "#502E92",
    fontSize: "15px",
    fontWeight: "bold",
    wordBreak: "break-word",
    width: "calc(98% - 100px)",
    marginTop: "30px",
    fontFamily: "Avenir_black !important",
  },
  typotext2: {
    color: "#502E92",
    fontSize: "15px",
    fontWeight: "bold",
    wordBreak: "break-word",
    width: "calc(100% - 90px)",
    marginTop: "30px",
    fontFamily: "Avenir_black !important",
  },
  iconnavigation: {
    display: "inline-flex",
    // float: "right",
    // marginTop: "-35px",
    color: "#502E92",
    fontSize: "29px",
  },
  appointmentcard: {
    width: "315px",
    height: "235px",
    backgroundColor: "#F8F6F6",
    alignItems: "center",
    boxShadow: "none",
  },
  patientname: {
    fontWeight: "bold",
  },
  appointmentHeading: {
    fontWeight: "bold",
    fontSize: "18px",
    color: "#424242",
    marginRight: "421px",
    marginLeft: "-21px",
    fontFamily: "Avenir_black !important",
  },
  appointmentHeading2: {
    fontWeight: "bold",
    fontSize: "18px",
    color: "#502E92",
    fontFamily: "Avenir_black !important",
    cursor: "pointer",
  },

  //   Up Coming Appt Card Style
  appointmentcard: {
    width: "100%",
    height: "100%",
    backgroundColor: "#F8F6F6",
    alignItems: "center",
    boxShadow: "none",
  },
  nameTypo: {
    fontWeight: "bold",
    paddingBottom: "10px",
    textTransform: "capitalize",
    fontSize: "15px",
    marginLeft: "15px",
    color: "#424242",
    fontFamily: "Avenir_heavy !important",
  },
  nameDoctor: {
    color: "#000000",
    fontSize: "13px",
    textTransform: "capitalize",
    marginLeft: "15px",
    // wordBreak: "break-word",
    // width: "calc(100% - 110px)",
    marginRight: "10px",
    display: "inline-flex",
    marginTop: "5px",
    fontFamily: "Avenir_heavy !important",
    fontWeight: "bold",
  },
  btnDiv: {
    borderRadius: "5px",
    border: " 1px solid #502E92",
    width: "135px",
    height: "40px",
    textAlign: "center",
    padding: "10px",
    fontSize: "12px",
    color: "#502E92",
    marginRight: "15px",
    cursor: "pointer",
  },
  editApmtText1: {
    color: "#555555",
    fontFamily: "Avenir_heavy !important",
    fontSize: "16px",
    margin: "10px 0",
  },
  editApmtText2: {
    color: "#555555",
    fontSize: "14px",
    marginTop: "10px",
  },
  editApmtBtn: {
    color: "#555555",
    margin: "5px 0",
    cursor: "pointer",
  },
  editApmtIcon: {
    height: "20px",
    margin: "-5px 0",
  },
  editApmtBtnText: {
    fontSize: "14px",
    display: "inline-block",
    marginTop: "20px",
    marginLeft: "10px",
  },
};
