apiVersion: v1
kind: Service
metadata:
  name: appointment-srv
spec:
  selector:
    app: appointment
  ports:
    - name: appointment
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment
  template:
    metadata:
      labels:
        app: appointment
    spec:
      containers:
        - name: appointment
          image: adhiman24/appointment
          livenessProbe:
            httpGet:
              path: /api/health/liveness
              port: 3000
              httpHeaders:
              - name: Host
                value: appointment-srv.default
            initialDelaySeconds: 15
            periodSeconds: 30
          env:
            - name: DATABACKUP_TAR_FILENAME
              value: employee
            - name: FILE_LOG_NAME
              value: 'appointmentLogger'
            - name: FILE_LOG_LEVEL
              value: 'info'
            - name: CONSOLE_LOG_LEVEL
              value: 'error'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: unifycare
            - name: MONGO_URI
              value: 'mongodb://appointment-mongo-srv:27017/appointment'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

