export enum EmailTemplate {
  WelcomeEmail = 'welcome',
  RegistrationDetails = 'Registration_Details',
  RamainderAppointmentForDoctor = 'Ramainder_Appointment_For_Doctor',
  AppointmentConfirmed = 'Appointment_Confirmed',
  AppointmentReschedule = 'Appointment_Reschedule',
  RegistrationSuccessful = 'Registration_Successful',
  RaminderAppointmentForPatient = 'Raminder_Appointment_For_Patient',
  AccountSuspended = 'Account_Suspended',
  MessageNotificationEmployee = 'Message_Notification_Employee',
  MessageNotificationPatient = 'Message_Notification_Patient',
  AppointmentCancelled = 'Appointment_Cancelled',
  OrderPaymentConfiramtion = 'Order_Payment_Confiramtion',
  ConsultationCompleted = 'Consultation_Completed',
  PharmacyOrder = 'Pharmacy_Order',
  LabOrder = 'Lab_Order',
  VerifyEmail = 'verify-email',
  ForgotPassword = 'forgot-password',
  PasswordReset = 'password-reset',
  TestPrescription = 'test-prescription',
  CustomerEmailInvite = 'customer-email-invite',
  NoTemplate = 'no-template',
}
