export enum MedicineDosageDuration {
  OneDay = 'one:day',
  TwoDays = 'two:days',
  ThreeDays = 'three:days',
  FourDays = 'four:days',
  FiveDays = 'five:days',
  SixDays = 'six:days',
  OneWeek = 'one:week',
  TwoWeeks = 'two:weeks',
  ThreeWeeks = 'three:weeks',
  FourWeeks = 'four:weeks',
  OneMonth = 'one:month',
  TwoMonths = 'two:months',
  ThreeMonths = 'three:months',
  FourMonths = 'four:months',
  FiveMonths = 'five:months',
  SixMonths = 'six:months',
}
