export enum SpecializationType {
  Medicine = 'medicine',
  Surgery = 'surgery',
  Gynaecology = 'gynaecology',
  Obstetrics = 'obstetrics',
  Paediatrics = 'paediatrics',
  Eye = 'eye',
  ENT = 'ENT',
  Dental = 'dental',
  Orthopaedics = 'orthopaedics',
  Neurology = 'neurology',
  Cardiology = 'cardiology',
  Psychiatry = 'psychiatry',
  Skin = 'skin',
  VD = 'vd',
  PlasticSurgery = 'plastic-surgery',
  NuclearMedicine = 'nuclear-medicine',
  InfectiousDisease = 'infectious-disease',
  Diabetic = 'diabetic',
  Physiotherapy = 'physiotherapy',
  HealthEducation = 'health-education',
  Counseling = 'counseling',
  Nutritionist = 'nutritionist',
}
