apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment
  template:
    metadata:
      labels:
        app: appointment
    spec:
      containers:
        - name: appointment
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          livenessProbe:
            httpGet:
              path: /api/health/liveness
              port: 3000
              scheme: 'HTTP'
            initialDelaySeconds: 180
            periodSeconds: 45
          readinessProbe:
            httpGet:
              path: /api/health/readiness
              port: 3000
              scheme: 'HTTP'
            initialDelaySeconds: 45
            periodSeconds: 30
          env:
#            - name: DEFAULT_ASSISTANT_EMAIL_ID
#              value: 'assistant1@diahome.com'
            - name: DEFAULT_ASSISTANT_MOBILE_NUMBER
              value: '9999900011'
            - name: GCS_BUCKET
              value: 'unifycare-dev-platform'
            - name: GCLOUD_PROJECT
              value: 'gamma-unify-care'
            - name: DATABACKUP_TAR_FILENAME
              value: Appointment.tar
            - name: FILE_LOG_NAME
              value: 'appointmentLogger'
            - name: FILE_LOG_LEVEL
              value: 'info'
            - name: CONSOLE_LOG_LEVEL
              value: 'error'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: unifycare-dev-platform
            - name: MONGO_URI
#              value: 'mongodb://appointment-mongo-srv:27017/appointment'
              value: 'mongodb+srv://appointment:jUIGMSqycprxMxyG@cluster0.3uj35.mongodb.net/appointment?retryWrites=true&w=majority'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-srv
spec:
  selector:
    app: appointment
  ports:
    - name: appointment
      protocol: TCP
      port: 3000
      targetPort: 3000
