export const doctorStyle = {
  card: {
    backgroundColor: "#F8F6F6",
    boxShadow: "none",
  },
  mainDiv: {
    height: "100%",
    width: "100%",
    objectFit: "contain",
    float: "left",
  },
  doctorImgDiv: {
    width: "100px",
    height: "100px",
    alignItems: "center",
    marginBottom: "15px",
    float: "left",
  },
  doctorDetailDiv: {
    float: "left",
    textAlign: "left",
    position: "relative",
  },
  doctorNameTypo: {
    paddingBottom: "10px",
    textTransform: "capitalize",
    fontSize: "20px",
    marginLeft: "15px",
    color: "#424242",
    marginBottom: "-10px",
    fontFamily: "Avenir_black !important",
  },
  qualificationTypo: {
    color: "#818080",
    fontSize: "13px",
    textTransform: "capitalize",
    marginLeft: "15px",
  },
  addressTypo: {
    color: "#555555",
    fontSize: "13px",
    textTransform: "capitalize",
    marginLeft: "15px",
    wordBreak: "break-word",
    width: "calc(100% - 110px)",
    display: "flex",
    marginTop: "5px",
    alignItems: "center",
  },
  locationImg: {
    color: "green",
    width: "20px",
    height: "20px",
    marginTop: "5px",
    marginRight: "7px",
  },

  bookSlottext: {
    textAlign: "right",
    marginRight: "20px",
    fontSize: "18px",
    fontWeight: "bold",
    marginTop: "10px",
    marginBottom: "-10px",
    color: "#424242",
    fontFamily: "Avenir_heavy !important",
  },
  bookSlottextsec: {
    textAlign: "right",
    marginRight: "20px",
    fontSize: "14px",
    marginBottom: " -10px",
    color: "#555555",
    fontFamily: "Avenir_heavy !important",
  },
  profileButton: {
    float: "right",
    marginTop: "25px",
    marginRight: "10px",
    textTransform: "capitalize",
    fontSize: "18px",
    color: "#502E92",
    fontWeight: "bold",
    "& span": {
      fontFamily: "Avenir_black !important",
    },
  },
  // Consultation Type Style
  mainHeading: {
    marginTop: "20px",
    marginBottom: "10px",
    fontSize: "20px",
    fontWeight: "bold",
    fontFamily: "Avenir_black !important",
    color: "#424242",
  },
  physicalRadioText: {
    display: "inline-flex",
    marginRight: "50px",
    marginLeft: "20px",
  },
  videoRadioText: {
    display: "inline-flex",
    marginLeft: "20px",
  },
  radioPhysicalImg: {
    marginRight: "15px",
    width: "20px",
    height: "20px",
  },
  radioVideoImg: {
    marginRight: "15px",
    width: "25px",
    height: "25px",
  },
  // Slot Date Picker Style
  selectWrapper: {
    display: "inline-block",
    overflow: "hidden",
    background: "#ffffff",
    paddingLeft: "8px",
    paddingRight: "15px",
    marginRight: "10px",
    color: "#555555",
    display: "flex",
    alignItems: "center",
    fontFamily: "Avenir_black !important",
  },
  slotBtn: {
    // backgroundColor: "rgb(0, 181, 175)",
    border: "1px solid #bebebe",
    width: "65px",
    height: "60px",
    textAlign: "center",
    paddingTop: "10px",
    fontSize: "15px",
    fontWeight: "bold",
    color: "#555555",
    borderRadius: "5px",
    marginLeft: "5px",
    cursor: "pointer",
    fontFamily: "Avenir_medium !important",
  },
  slotBtnActive: {
    backgroundColor: "#00B5AF",
    // border: "1px solid #bebebe",
    width: "65px",
    height: "60px",
    textAlign: "center",
    paddingTop: "10px",
    fontSize: "15px",
    fontWeight: "bold",
    color: "#FFFFFF",
    borderRadius: "5px",
    marginLeft: "5px",
    cursor: "pointer",
    fontFamily: "Avenir_medium !important",
  },
  // Available Slot Style
  slotMainHeading: {
    fontSize: "18px",
    fontWeight: "bold",
    paddingTop: "5px",
    color: "#424242",
    fontFamily: "Avenir_black !important",
  },
  AccordionSummary: {
    "&.MuiAccordionSummary-root": {
      display: "inline-flex",
      padding: "0px 16px",
      minHeight: "48px",
      transition:
        "min-height 150ms cubic-bezier(0.4, 0, 0.2, 1) 0ms,background-color 150ms cubic-bezier(0.4, 0, 0.2, 1) 0ms;",
    },
  },
  morningSlotBtn: {
    border: "1px solid #9E9E9E",
    backgroundColor: "#fff",
    color: "#555555",
    fontSize: "12px",
    fontFamily: "Avenir_heavy !important",
    fontWeight: "bold",
    width: "100px",
    marginRight: "10px",
  },
  morningSlotBtnActive: {
    border: "1px solid #00B2A9",
    backgroundColor: "#00B2A9",
    color: "#fff",
    fontSize: "12px",
    width: "100px",
    fontFamily: "Avenir_heavy !important",
    marginRight: "10px",
    "&:hover": {
      backgroundColor: "#00B2A9",
      color: "#fff",
    },
  },
  dayText: {
    fontFamily: "Avenir_heavy !important",
    fontWeight: "bold",
    color: "#424242",
  },
  dayTextEven: {
    fontFamily: "Avenir_heavy !important",
    fontWeight: "bold",
    color: "#424242",
    marginRight: "12px",
  },
  // Bill Details
  billMainDiv: {
    backgroundColor: "#F9F9F9",
    padding: "20px",
  },
  billMinHeading: {
    fontWeight: "bold",
    marginBottom: "15px",
    fontFamily: "Avenir_heavy !important",
    color: "#545454",
  },
  billText1: {
    display: "flex",
    width: "300px",
    alignItems: "center",
    color: "#545454",
  },
  billText2: {
    alignItems: "center",
    display: "flex",
    marginLeft: "200px",
    marginTop: "-20px",
    width: "50px",
    fontWeight: "600",
    color: "#545454",
  },
  billText3: {
    display: "flex",
    width: "300px",
    alignItems: "center",
    color: "#545454",
    marginTop: "3px",
  },
  billText4: {
    alignItems: "center",
    display: "flex",
    marginLeft: "200px",
    marginTop: "-20px",
    width: "50px",
    fontWeight: "600",
    color: "#545454",
  },
  totalBillText: {
    fontWeight: "bold",
    marginTop: "15px",
    color: "#545454",
    fontFamily: "Avenir_heavy !important",
  },
  totalbillRs: {
    marginLeft: "200px",
    marginTop: "-25px",
    alignItems: "center",
    fontWeight: "bold",
    color: "#545454",
    fontFamily: "Avenir_heavy !important",
  },
};
