export const PastAppointmentStyle = {
  appointmentcard: {
    width: "100%",
    height: "100%",
    backgroundColor: "#F8F6F6",
    alignItems: "center",
    boxShadow: "none",
  },
  nameTypo: {
    fontWeight: "bold",
    paddingBottom: "10px",
    textTransform: "capitalize",
    fontSize: "20px",
    marginLeft: "15px",
    color: "#424242",
    fontFamily: "Avenir_heavy !important",
  },
  nameDoctor: {
    color: "#555555",
    fontSize: "13px",
    textTransform: "capitalize",
    marginLeft: "15px",
    // wordBreak: "break-word",
    // width: "calc(100% - 110px)",
    marginRight: "10px",
    display: "inline-flex",
    marginTop: "5px",
    fontFamily: "Avenir_heavy !important",
    fontWeight: "bold",
  },
  btnDiv: {
    borderRadius: "5px",
    border: " 1px solid #502E92",
    width: "200px",
    height: "35px",
    textAlign: "center",
    padding: "10px",
    fontSize: "13px",
    color: "#502e92",
    marginRight: "26px",
  },
  editApmtText1: {
    color: "#555555",
    fontFamily: "Avenir_heavy !important",
    fontSize: "16px",
    margin: "10px 0",
  },
  editApmtText2: {
    color: "#555555",
    fontSize: "14px",
    marginTop: "10px",
  },
  editApmtBtn: {
    color: "#555555",
    margin: "5px 0",
    cursor: "pointer",
  },
  editApmtIcon: {
    height: "20px",
    margin: "-5px 0",
  },
  editApmtBtnText: {
    fontSize: "14px",
    display: "inline-block",
    marginTop: "20px",
    marginLeft: "10px",
  },
};
