apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utility
  template:
    metadata:
      labels:
        app: utility
    spec:
      containers:
        - name: utility
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          # livenessProbe:
          #   httpGet:
          #     path: /api/health/liveness
          #     port: 3000
          #     scheme: 'HTTP'
          #   initialDelaySeconds: 150
          #   periodSeconds: 30
          # readinessProbe:
          #   httpGet:
          #     path: /api/health/readiness
          #     port: 3000
          #     scheme: 'HTTP'
          #   initialDelaySeconds: 60
          #   periodSeconds: 30
          env:
            - name: SYSTEM_SMS_SENDER_ID
              value: unifycare-dev-platform
            - name: SYSTEM_SENDER_FULL_NAME
              value: 'unifycare-dev-platform'
            - name: SYSTEM_SENDER_EMAIL_ID
              value: 'noreply@unify.care'
            - name: SYSTEM_RECEIVER_EMAIL_ID
              value: 'avadeshc@unifytech.com'
            - name: DATABACKUP_TAR_FILENAME
              value: Utility.tar
            - name: FILE_LOG_NAME
              value: 'utilityLogger'
            - name: FILE_LOG_LEVEL
              value: 'info'
            - name: CONSOLE_LOG_LEVEL
              value: 'error'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: unifycare-dev-platform
            - name: MONGO_URI
              value: 'mongodb+srv://utility:SFZfWYIOccejtplu@cluster0.3uj35.mongodb.net/utility?retryWrites=true&w=majority'
            - name: GCS_BUCKET
              value: 'gamma-unify-care-bucket-1'
            - name: GCLOUD_PROJECT
              value: 'gamma-unify-care'
            - name: GCS_KEYFILE
              value: './key.json'
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: './key.json'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: utility-srv
spec:
  selector:
    app: utility
  ports:
    - name: utility
      protocol: TCP
      port: 3000
      targetPort: 3000
