apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: patientpf-unifycare-tls
spec:
  secretName: patientpf-unifycare-crt
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: patientpf.unify.care
  dnsNames:
    - patientpf.unify.care
    