-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg62EzPy5ByNY/RRb0
kN9IswBsis1ZAJcx4PN1PHYGMaqgCgYIKoZIzj0DAQehRANCAARqK+MbhfxxfxH0
akPmflSnHtpju75BRxsurbuYsVAvUuDKFg+24ojp3ZLlunCmA1C0J/sGVKXAaTBQ
ab4Z0RlG
-----END PRIVATE KEY-----