name: tests-patient

on:
  pull_request:
    paths:
      - 'patient/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd patient && npm install && npm run test:ci
