name: tests-partner

on:
  pull_request:
    paths:
      - 'partner/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd partner && npm install && npm run test:ci
